[workspace]
members = [
    "moltendb-core",
    "moltendb-auth",
    "moltendb-wasm",
    "moltendb-server",
]
resolver = "2"

[profile.release]
opt-level = 3        # Optimize for maximum runtime performance (speed over size)
lto = "fat"          # Equivalent to `true`, enables aggressive cross-crate optimization
codegen-units = 1    # Maximum optimization at the cost of compile time
strip = true         # Removes symbols (keeps binary small without hurting speed)
panic = "abort"      # Removes unwinding code, slightly improving performance



